# Hyperspace Build
trigger:
  batch: true
  branches:
    include:
      - master

jobs:
  - job: Build_2_11
    displayName: 'Build sources and run unit tests for Scala 2.11'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - task: JavaToolInstaller@0
        displayName: 'Set Java version'
        inputs:
          versionSpec: '8'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
      - script: sbt ++2.11.12 clean
        displayName: 'Running $sbt clean'
      - script: sbt ++2.11.12 update
        displayName: 'Running $sbt update'
      - script: sbt ++2.11.12 compile
        displayName: 'Running $sbt compile'
      - script: sbt ++2.11.12 test
        displayName: 'Running $sbt test'
      # If not a pull request, publish artifacts.
      - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        - script: sbt ++2.11.12 package
          displayName: 'Running $sbt package'
        - task: CopyFiles@2
          displayName: 'Copy hyperspace-core JAR'
          inputs:
            sourceFolder: '$(Build.SourcesDirectory)/target/'
            contents: '**/*.jar'
            targetFolder: '$(Build.ArtifactStagingDirectory)/hyperspace-core/'
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Hyperspace artifacts'
          inputs:
            artifactName: 'hyperspace-core'
            pathtoPublish: '$(Build.ArtifactStagingDirectory)/hyperspace-core/'
      - script: sbt ++2.12.8 clean
        displayName: 'Running $sbt clean'
      - script: sbt ++2.12.8 update
        displayName: 'Running $sbt update'
      - script: sbt ++2.12.8 compile
        displayName: 'Running $sbt compile'
      - script: sbt ++2.12.8 test
        displayName: 'Running $sbt test'
      # If not a pull request, publish artifacts.
      - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        - script: sbt ++2.12.8 package
          displayName: 'Running $sbt package'
        - task: CopyFiles@2
          displayName: 'Copy hyperspace-core JAR'
          inputs:
            sourceFolder: '$(Build.SourcesDirectory)/target/'
            contents: '**/*.jar'
            targetFolder: '$(Build.ArtifactStagingDirectory)/hyperspace-core/'
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Hyperspace artifacts'
          inputs:
            artifactName: 'hyperspace-core'
            pathtoPublish: '$(Build.ArtifactStagingDirectory)/hyperspace-core/'
